server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka-server:${server.port}/eureka/
  server:
    #该机制是Eureka Server的自我保护机制，该机制会使注册中心所维护的实例不是很准确，在本地开发时，可以将该参数关闭以确保注册中心将不可用的实例正确删除
    enable-self-preservation: false
    #清理无效节点的时间间隔 （单位毫秒，默认60*1000）
    eviction-interval-timer-in-ms: 30000
security:
  basic:
    enabled: true #默认为false，true的话客户端要用用户名密码连接，不然注册的客户端会连不上eureka服务端
  user:
    password: 123456
    name: admin