version: '3.0'
services:
  eureka:
    image: fzm-tcm-eureka
    restart: always
    tty: true
    container_name: fzm-tcm-eureka
    environment:
    - TZ=Asia/Shanghai
    ports:
    - "1111:1111"
  service:
    image: fzm-tcm-front
    restart: always
    tty: true
    container_name: fzm-tcm-front
    environment:
    - TZ=Asia/Shanghai
    ports:
    - "8008:8008"
    volumes:
    - ${HOME}/fzm-tcm/fzm-tcm-front/logs:${HOME}/logs

