version: '3.0'
services:
  eureka:
    image: eureka_server
    restart: always
    tty: true
    container_name: eureka_server
    environment:
    - TZ=Asia/Shanghai
    - EUREKA_INSTANCE_IP-ADDRESS=172.16.100.31
    - EUREKA_HOST=172.16.100.31
    ports:
    - "8761:8761"
  service:
    image: service_a
    restart: always
    tty: true
    container_name: service_a
    environment:
    - TZ=Asia/Shanghai
    - EUREKA_INSTANCE_IP-ADDRESS=172.16.100.31
    - EUREKA_HOST=172.16.100.31
    ports:
    - "7901:7901"
    volumes:
    - ${HOME}/springcloud-demo/service/logs:${HOME}/logs

